src/Entity/Lesson.php
<?php

namespace App\Entity;

use App\Repository\LessonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LessonRepository::class)]
class Lesson
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Sport::class,inversedBy: 'lessons')]
    private ?Sport $Name = null;

    #[ORM\Column]
    private ?int $NbPlace = null;

    #[ORM\ManyToOne(targetEntity: Location::class,inversedBy: 'lessons')]
    private ?Location $location = null;

    #[ORM\ManyToOne(inversedBy: 'lessons')]
    private ?Coach $Coach = null;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'lessons')]
    private Collection $Participants;

    #[ORM\Column(length: 7)]
    private ?string $background_color = null;

    #[ORM\Column(length: 7)]
    private ?string $border_color = null;

    #[ORM\Column(length: 7)]
    private ?string $text_color = null;


    #[ORM\ManyToOne(inversedBy: 'lessons')]
    private ?State $state = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end = null;

    #[ORM\Column]
    private ?bool $all_day = null;

    public function __construct()
    {
        $this->Participants = new ArrayCollection();
        $this->State = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?Sport
    {
        return $this->Name;
    }

    public function setName(?Sport $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getNbPlace(): ?int
    {
        return $this->NbPlace;
    }

    public function setNbPlace(int $NbPlace): self
    {
        $this->NbPlace = $NbPlace;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getCoach(): ?Coach
    {
        return $this->Coach;
    }

    public function setCoach(?Coach $Coach): self
    {
        $this->Coach = $Coach;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getParticipants(): Collection
    {
        return $this->Participants;
    }

    public function addParticipant(User $participant): self
    {
        if (!$this->Participants->contains($participant)) {
            $this->Participants[] = $participant;
            $this->Participants->add($participant);
        }

        return $this;
    }

    public function removeParticipant(User $participant): self
    {
        $this->Participants->removeElement($participant);

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): self
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function getBorderColor(): ?string
    {
        return $this->border_color;
    }

    public function setBorderColor(string $border_color): self
    {
        $this->border_color = $border_color;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->text_color;
    }

    public function setTextColor(string $text_color): self
    {
        $this->text_color = $text_color;

        return $this;
    }

    public function getState(): ?State
    {
        return $this->state;
    }

    public function setState(?State $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function addState(State $state): self
    {
        if (!$this->State->contains($state)) {
            $this->State->add($state);
            $state->setLesson($this);
        }

        return $this;
    }

    public function removeState(State $state): self
    {
        if ($this->State->removeElement($state)) {
            // set the owning side to null (unless already changed)
            if ($state->getLesson() === $this) {
                $state->setLesson(null);
            }
        }

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function isAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(bool $all_day): self
    {
        $this->all_day = $all_day;

        return $this;
    }


}

src/Form/LessonType.php
<?php

namespace App\Form;

use App\Entity\Coach;
use App\Entity\Lesson;
use App\Entity\Location;
use App\Entity\Sport;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LessonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Name', EntityType::class,[
                'class' => Sport::class,
                'choice_label' => 'name',

            ])
            ->add('Start', DateTimeType::class, [
                'date_widget' => 'single_text',
                'time_widget' => 'single_text',
            ])
            ->add('end', DateTimeType::class, [
                'date_widget' => 'single_text',
                'time_widget' => 'single_text',
            ])
            ->add('NbPlace')
            ->add('background_color',ChoiceType::class,

                array(
                    'choices'=>array(
                        'jaune safran'=> '#EAC435' ,
                        'jaune vif'=> '#FCAB10',

                        'tarte orange'=> '#FB4D3D',
                        'Coquelicot '=> '#F15025',
                        'orange carotte '=> '#F18F01',

                        'bleue ébloui'=> '#345995',
                        'poudre bleue'=> '#A0D2DB',
                        'bleue saphire'=> '#006E90',

                        'Rouge rubis'=> '#CA1551',
                        'Rouge feu'=> '#E3655B',

                        'Vert Caraibes'=> '#03CEA4',
                        'Vert moyen'=> '#5B8C5A',
                        'Vert-'=> '#13EB73',
                        'Vert océan'=> '#48BF84',
                        'Vert émeraude'=> '#439775',
                        'Vert myrte'=> '#32746D',

                        'Violet'=> '#726DA8',
                        'Violet lilas'=> '#89608E',
                        'Violet sombre'=> '#623B5A',

                        'rose de chine'=> '#E072A4',
                        'rose clair'=> '#FFA5AB',
                        'rose lavande'=> '#D8A7CA',
                        'noir'=> 'black',
                    )
                ))
            ->add('AllDay', ChoiceType::class,
            array(
                'choices'=>array(
                    'non'=> 'false',
                    'oui'=> 'true'
                )

            ))
            ->add('border_color',ChoiceType::class,
                array(
                    'choices'=>array(
                        'jaune safran'=> '#EAC435',
                        'jaune vif'=> '#FCAB10',

                        'tarte orange'=> '#FB4D3D',
                        'Coquelicot '=> '#F15025',
                        'orange carotte '=> '#F18F01',

                        'bleue ébloui'=> '#345995',
                        'poudre bleue'=> '#A0D2DB',
                        'bleue saphire'=> '#006E90',

                        'Rouge rubis'=> '#CA1551',
                        'Rouge feu'=> '#E3655B',

                        'Vert Caraibes'=> '#03CEA4',
                        'Vert moyen'=> '#5B8C5A',
                        'Vert-'=> '#13EB73',
                        'Vert océan'=> '#48BF84',
                        'Vert émeraude'=> '#439775',
                        'Vert myrte'=> '#32746D',

                        'Violet'=> '#726DA8',
                        'Violet lilas'=> '#89608E',
                        'Violet sombre'=> '#623B5A',

                        'rose de chine'=> '#E072A4',
                        'rose clair'=> '#FFA5AB',
                        'rose lavande'=> '#D8A7CA',
                        'noir'=> 'black',
                    )

                ))
            ->add('text_color',ChoiceType::class,
                array(
                    'choices'=>array(
                        'jaune safran'=> '#EAC435',
                        'jaune vif'=> '#FCAB10',

                        'tarte orange'=> '#FB4D3D',
                        'Coquelicot '=> '#F15025',
                        'orange carotte '=> '#F18F01',

                        'bleue ébloui'=> '#345995',
                        'poudre bleue'=> '#A0D2DB',
                        'bleue saphire'=> '#006E90',

                        'Rouge rubis'=> '#CA1551',
                        'Rouge feu'=> '#E3655B',

                        'Vert Caraibes'=> '#03CEA4',
                        'Vert moyen'=> '#5B8C5A',
                        'Vert-'=> '#13EB73',
                        'Vert océan'=> '#48BF84',
                        'Vert émeraude'=> '#439775',
                        'Vert myrte'=> '#32746D',

                        'Violet'=> '#726DA8',
                        'Violet lilas'=> '#89608E',
                        'Violet sombre'=> '#623B5A',

                        'rose de chine'=> '#E072A4',
                        'rose clair'=> '#FFA5AB',
                        'rose lavande'=> '#D8A7CA',
                        'noir'=> 'black',
                    )

                ))
            ->add('Location', EntityType::class, [
                'class' => Location::class,
                'choice_label' => 'name',
            ])
            ->add('Coach' ,EntityType::class, [
                'class' => Coach::class,
                'choice_label' => 'name',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Lesson::class,
        ]);
    }
}

src/Controller/LessonController.php
<?php

namespace App\Controller;

use App\Entity\Lesson;
use App\Form\LessonType;
use App\Repository\LessonRepository;
use App\Repository\StateRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/lesson')]
class LessonController extends AbstractController
{

    #[Route('/', name: 'app_lesson_index', methods: ['GET'])]
    public function index(LessonRepository $lessonRepository): Response
    {
        if (!$this->isGranted('IS_AUTHENTICATED_FULLY')) {
            return $this->redirectToRoute('app_login');
        }
        return $this->render('lesson/index.html.twig', [
            'lessons' => $lessonRepository->findAll(),

        ]);
    }



    /*************************** New lesson ***************************/
    /*******************************************************************/
    #[Route('/new', name: 'app_lesson_new', methods: ['GET', 'POST'])]
    public function new(Request $request, LessonRepository $lessonRepository, StateRepository $stateRepository): Response
    {

        if (!$this->isGranted('IS_AUTHENTICATED_FULLY')) {
            return $this->redirectToRoute('app_login');
        }
        $lesson = new Lesson();
        $form = $this->createForm(LessonType::class, $lesson);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $state = $stateRepository->findOneBy(['wording' => 'Activity opened']);
            $lesson->setState($state);
            $lessonRepository->save($lesson, true);

            return $this->redirectToRoute('app_planning', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('lesson/new.html.twig', [
            'lesson' => $lesson,
            'form' => $form,
        ]);
    }


    /*************************** Show lesson ***************************/
    /*******************************************************************/
    #[Route('/{id}', name: 'app_lesson_show', methods: ['GET'])]
    public function show(Lesson $lesson): Response
    {
        if (!$this->isGranted('IS_AUTHENTICATED_FULLY')) {
            return $this->redirectToRoute('app_login');
        }
        return $this->render('lesson/show.html.twig', [
            'lesson' => $lesson,
        ]);
    }


    /*************************** Modify lesson ***************************/
    /*********************************************************************/
    #[Route('/{id}/edit', name: 'app_lesson_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Lesson $lesson, LessonRepository $lessonRepository, StateRepository $stateRepository): Response
    {
        if (!$this->isGranted('IS_AUTHENTICATED_FULLY')) {
            return $this->redirectToRoute('app_login');
        }
        $form = $this->createForm(LessonType::class, $lesson);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $lessonRepository->save($lesson, true);

            return $this->redirectToRoute('app_lesson_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('lesson/edit.html.twig', [
            'lesson' => $lesson,
            'form' => $form,
        ]);
    }


    /*************************** Delete lesson ***************************/
    /*********************************************************************/
    #[Route('/{id}', name: 'app_lesson_delete', methods: ['POST'])]
    public function delete(Request $request, Lesson $lesson, LessonRepository $lessonRepository): Response
    {
        if (!$this->isGranted('IS_AUTHENTICATED_FULLY')) {
            return $this->redirectToRoute('app_login');
        }
        if ($this->isCsrfTokenValid('delete'.$lesson->getId(), $request->request->get('_token'))) {
            $lessonRepository->remove($lesson, true);
        }

        return $this->redirectToRoute('app_lesson_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/lesson/_delete_form.html.twig
<form method="post" action="{{ path('app_lesson_delete', {'id': lesson.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lesson.id) }}">
    <button class="btn-show-delete">Delete</button>
</form>

templates/lesson/_form.html.twig
{{ form_start(form) }}

<div class="container-edit">

    {{ form_row(form.Name) }}
    {{ form_row(form.Start) }}
    {{ form_row(form.end) }}
    {{ form_row(form.NbPlace) }}
    {{ form_row(form.AllDay) }}
    {{ form_row(form.Location) }}
    {{ form_row(form.Coach) }}
    {{ form_row(form.background_color) }}
    {{ form_row(form.border_color) }}
    {{ form_row(form.text_color) }}

    <button  class="btn-show-save" >{{ button_label|default('Save') }}</button>
    <a class="btn-show-retour" href="{{ path('app_planning') }}">Retour</a>
</div>


{{ form_end(form) }}

templates/lesson/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Lesson{% endblock %}

{% block body %}
    <h1>Edit Lesson</h1>

    {{ include('lesson/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn-show-retour" href="{{ path('app_lesson_index') }}">back to list</a>

    {{ include('lesson/_delete_form.html.twig') }}

{% endblock %}

templates/lesson/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}list des leçons{% endblock %}

{% block body %}
    <h1>list des leçons</h1>

    <table class="table-info">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>HeureDebut</th>
                <th>HeureFin</th>
                <th>NbPlace</th>
                <th>Background_color</th>
                <th>allday</th>
                <th>Border_color</th>
                <th>Text_color</th>
                <th>Coach</th>
                <th>Lieux</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for lesson in lessons %}
            <tr>
                <td>{{ lesson.id }}</td>
                <td>{{ lesson.Name.Name }}</td>
                <td>{{ lesson.start ? lesson.start|date('y-m-d H:i:s') : '' }}</td>
                <td>{{ lesson.end ? lesson.end|date('y-m-d H:i:s') : '' }}</td>
                <td>{{ lesson.NbPlace }}</td>
                <td>{{ lesson.backgroundColor }}</td>
                <td>{{ lesson.allDay}}</td>
                <td>{{ lesson.borderColor }}</td>
                <td>{{ lesson.textColor }}</td>
                <td>{{ lesson.coach }}</td>
                <td>{{ lesson.location }}</td>
                <td>
                    <a class="btn-action" href="{{ path('app_lesson_show', {'id': lesson.id}) }}">show</a>
                    <a class="btn-action" href="{{ path('app_lesson_edit', {'id': lesson.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn-add" href="{{ path('app_lesson_new') }}">Ajouter une leçon</a>
{% endblock %}

templates/lesson/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}leçon{% endblock %}

{% block body %}
    <h1 id="title-new-lesson">créer une nouvelle leçon</h1>

    <div id="Block-new-Lesson">
        {{ include('lesson/_form.html.twig') }}


    </div>

{% endblock %}

templates/lesson/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}leçon{% endblock %}

{% block body %}
    <h1>leçon</h1>

    <table class="table-info">
        <tbody>
            <tr>
                <th>Name</th>
                <td>{{ lesson.Name.Name }}</td>
            </tr>
            <tr>
                <th>StartTime</th>
                <td>{{ lesson.start ? lesson.start|date('y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>EndTime</th>
                <td>{{ lesson.end ? lesson.end|date('y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>NbPlace</th>
                <td>{{ lesson.NbPlace }}</td>
            </tr>
            <tr>
                <th>day</th>
                <td>{{ lesson.allday }}</td>
            </tr>
            <tr>
                <th>Border_color</th>
                <td>{{ lesson.borderColor }}</td>
            </tr>
            <tr>
                <th>Text_color</th>
                <td>{{ lesson.textColor }}</td>
            </tr>
            <tr>
                <th>Coach</th>
                <td>{{ lesson.Coach }}</td>
            </tr>
            <tr>
                <th>Lieux</th>
                <td>{{ lesson.location }}</td>
            </tr>
        </tbody>
    </table>

    <div class="container-btn-show">
        <a class="btn-show-retour" href="{{ path('app_planning') }}">Retour</a>

        <a class="btn-show-save" href="{{ path('app_lesson_edit', {'id': lesson.id}) }}">edit</a>

        {{ include('lesson/_delete_form.html.twig') }}
    </div>

{% endblock %}