src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = ['ROLE_USER'];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\ManyToMany(targetEntity: Lesson::class, mappedBy: 'Participants')]
    private Collection $lessons;

    #[ORM\Column(length: 255)]
    private ?string $FirstName = null;

    #[ORM\Column(length: 255)]
    private ?string $LastName = null;

    #[ORM\Column(type: 'string',nullable: true)]
    private $brochureFilename;

    public function __construct()
    {
        $this->lessons = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Lesson>
     */
    public function getLessons(): Collection
    {
        return $this->lessons;
    }

    public function addLesson(Lesson $lesson): self
    {
        if (!$this->lessons->contains($lesson)) {
            $this->lessons->add($lesson);
            $lesson->addParticipant($this);
        }

        return $this;
    }

    public function removeLesson(Lesson $lesson): self
    {
        if ($this->lessons->removeElement($lesson)) {
            $lesson->removeParticipant($this);
        }

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }
    public function getBrochureFilename()
    {
        return $this->brochureFilename;
    }

    public function setBrochureFilename($brochureFilename)
    {
        $this->brochureFilename = $brochureFilename;

        return $this;
    }
}

templates/Footer.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="initial-scale=1.0 , minimum-scale=1.0 , maximum-scale=1.0" />
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block Footer %}
            <div id="Footer-social-logo">
                <div>
                    <img id="Image-footer-insta" src="{{ asset('Directory/Image-footer-insta.png') }}" alt="Image-footer-insta">
                    <img id="Image-footer-Facbook" src="{{ asset('Directory/Image-footer-Facbook.png') }}" alt="Image-footer-Facbook">
                    <img id="Image-footer-linkedin" src="{{ asset('Directory/Image-footer-linkedin.png') }}" alt="Image-footer-linkedin">
                    <img id="Image-footer-Mail" src="{{ asset('Directory/Image-footer-Mail.png') }}" alt="Image-footer-Mail">
                </div>
                <div>
                    <img id="Image-footer-Sport-multisport-santé" src="{{ asset('Directory/Image-footer-Sport-multisport-santé.png') }}" alt="Image-footer-Sport-multisport-santé">
                </div>
            </div>
            <div id="Footer-link-legal">
                <a id="Mention-legales" href="{{path('app_home')}}"> <h2>Mention legales</h2></a>
                <a id="politique-confidentialité" href="{{path('app_home')}}"> <h2>politique de confidentialité</h2></a>
            </div>
        {% endblock %}
    </body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="initial-scale=1.0 , minimum-scale=1.0 , maximum-scale=1.0" />
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}

        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            <script>
                function openAccountModal(){
                    // When the user clicks the button, open the modal
                    let modalAccount = document.getElementById("modalAccount");
                    modalAccount.style.display = "block";
                }
            </script>
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block header %}

            <ul id="nav-bar">
                <a id="title" href="{{path('app_home')}}"> <h2>AssoSport</h2></a>

                <div id="AllLink">
                    <li>
                        <a class="link-nav-bar" href="{{path('app_home')}}" title="Accueil">Accueil</a>
                    </li>
                    <li>
                        <a class="link-nav-bar" href="{{path('app_planning')}}" title="Planning">Planning</a>
                    </li>
                    {% if app.user%}
                        <li>
                            <a class="link-nav-bar" href="{{path('app_reservation')}}" title="Réservation">Mes Réservation</a>
                        </li>
                    {% endif %}
                </div>

                {% if app.user%}
                    {%if app.user.brochureFilename%}
                        <div id="account-image" >
                            <img id="img-profil" src="{{ asset(app.user.brochureFilename)}}" alt="Image de profil" onclick="document.getElementById('modalAccount').style.display='block'" >
                        </div>
                    {%else%}
                        <div id="account-image" >
                            <img id="img-profil" src="{{ asset('Directory/IconProfil.png')}}" alt="Image de profil" onclick="document.getElementById('modalAccount').style.display='block'">
                        </div>
                    {%endif%}
                {% else %}
                    <div>
                        <a id="link-connection" href="{{path('app_login')}}" title="Se_Connecter">Se Connecter</a>
                    </div>
                {% endif %}
            </ul>

            {% if app.user%}
                <div id="modalAccount">

                    <span onclick="document.getElementById('modalAccount').style.display='none'" id="closeAccountModal" title="Close Modal">×</span>

                    <div id="InformationProfile">
                        {%if app.user.brochureFilename%}
                            <div id="account-image" >
                                <img id="img-profil" src="{{ asset(app.user.brochureFilename)}}" alt="Image de profil" onclick="document.getElementById('modalAccount').style.display='block'" >
                            </div>
                        {%else%}
                            <div id="account-image" >
                                <img id="img-profil" src="{{ asset('Directory/IconProfil.png')}}" alt="Image de profil" onclick="document.getElementById('modalAccount').style.display='block'">
                            </div>
                        {%endif%}
                        {% if app.user%}
                            <p id="">{{app.user.firstName}} {{app.user.lastName}}</p>
                            <p>{{ app.user.email }}</p>
                            <button id="btn-modifierProfile" href="{{path('app_user_profile')}}"><a  href="{{path('app_user_profile')}}" style="color: #B0413E" >Modifier le Profil</a></button>
                        {% endif %}
                    </div>

                    <div id="link-admin">
                        {% if is_granted('ROLE_ADMIN') %}
                            <a class="" href="{{path('app_lesson_index')}}" title="Liste des leçons">Liste des Leçons</a>

                            <a class="" href="{{path('app_coach')}}" title="Liste des coach">Liste des Coach</a>

                            <a class="" href="{{path('app_sport')}}" title="Liste des sports">Liste des Sports</a>

                        {% elseif is_granted('ROLE_USER') %}
                            <a class="" href="{{path('app_home')}}" title="Nous_Contacter">Nous Contacter</a>

                        {% endif %}
                    </div>

                    <a id="logout" href="{{path('app_logout')}}">Se Déconnecter</a>
                </div>
            {% endif %}
        {% endblock %}

        {% block body %}
        {% endblock %}
    </body>
</html>